/**
 * Kampala International University (KIU) — Structured questionnaire on prevalence, determinants and consequences of food insecurity among students
 * Google Sheet inbox for the online questionnaire at /kiu-food-study/
 * and data feed for the live dashboard at /kiu-food-study/dashboard/.
 *
 * GENERATED by scripts/build-content.js from scripts/lib/research/kiu-food-study.js,
 * scripts/lib/research/sheet-runtime.gs and js/research-analytics.js. Edit those files, rebuild, then paste this file again.
 *
 * Creates three tabs:
 *   Responses  one row per respondent, with computed FIES and IDDS scores
 *   Summary    live totals by campus, FIES category and IDDS class
 *   Codebook   every column with the verbatim question and its coding
 *
 * Setup (once), signed into the Learn n'lunch Google account:
 * 1. Create a new Google Sheet for this study and keep its sharing Restricted
 * 2. Extensions → Apps Script, delete the default code and paste this entire file
 * 3. Save, then Run → setupWorkbook (Authorize when Google asks)
 * 4. Deploy → New deployment → Type: Web app
 *      Execute as: Me
 *      Who has access: Anyone
 * 5. Copy the web app URL into content/pages/kiu-food-study.md as submitEndpoint and rebuild the site
 *
 * After changing the questionnaire: paste this file over the old code, Save, Run → setupWorkbook,
 * then Deploy → Manage deployments → Edit (pencil) → Version: New version → Deploy (same URL).
 * New columns are inserted before "Notes"; existing rows are left untouched.
 *
 * Live dashboard:
 *   Run → showDashboardKey      prints the research team's access key in the execution log
 *   Run → resetDashboardKey     issues a new key (the old one stops working)
 *   Run → openDashboardToPublic / closeDashboardToPublic   presentation-day switch (also available on the dashboard)
 *   Type EXCLUDE at the start of a response's Notes cell to drop it from the dashboard.
 */

// Leave empty when this script is bound to the study spreadsheet (Extensions → Apps Script).
var SPREADSHEET_ID = "";

var STUDY = {
  "id": "kiu-food-study",
  "version": "2026-10-07",
  "title": "Structured questionnaire on prevalence, determinants and consequences of food insecurity among students",
  "institution": "Kampala International University (KIU)",
  "consent": {
    "question": "A1",
    "yes": "Yes, I consent",
    "ageQuestion": "A2",
    "ageYes": "Yes"
  },
  "scoring": {
    "fies": {
      "items": [
        "D1",
        "D2",
        "D3",
        "D4",
        "D5",
        "D6",
        "D7",
        "D8"
      ],
      "yes": "Yes",
      "categories": [
        {
          "max": 0,
          "label": "Food secure"
        },
        {
          "max": 3,
          "label": "Mildly food insecure"
        },
        {
          "max": 6,
          "label": "Moderately food insecure"
        },
        {
          "max": 8,
          "label": "Severely food insecure"
        }
      ]
    },
    "idds": {
      "question": "F",
      "categories": [
        {
          "max": 3,
          "label": "Low dietary diversity"
        },
        {
          "max": 5,
          "label": "Medium dietary diversity"
        },
        {
          "max": 10,
          "label": "High dietary diversity"
        }
      ]
    }
  },
  "analysis": {
    "publicMinCell": 5,
    "fastMinutes": 5,
    "filters": [
      "CAMPUS",
      "B2",
      "B3",
      "B4",
      "B5",
      "B6"
    ],
    "ageBands": [
      {
        "max": 20,
        "label": "18–20"
      },
      {
        "max": 23,
        "label": "21–23"
      },
      {
        "max": 26,
        "label": "24–26"
      },
      {
        "max": 200,
        "label": "27+"
      }
    ],
    "sample": [
      "CAMPUS",
      "B2",
      "AGE_BAND",
      "B3",
      "B4",
      "B5",
      "B6"
    ],
    "determinants": [
      {
        "group": "Demographic factors",
        "ids": [
          "CAMPUS",
          "AGE_BAND",
          "B2",
          "B3",
          "B4",
          "B5",
          "B6",
          "B7"
        ]
      },
      {
        "group": "Socio-economic factors",
        "ids": [
          "C1",
          "C2",
          "C3",
          "C4",
          "C5",
          "C6",
          "C7"
        ]
      }
    ],
    "outcomes": [
      {
        "id": "H1",
        "label": "Missed at least one lecture due to hunger (30 days)",
        "not": [
          "None"
        ]
      },
      {
        "id": "G1",
        "label": "Typically eats only one meal a day",
        "any": [
          "1 meal"
        ]
      },
      {
        "id": "H3.1",
        "label": "Difficulty concentrating in class due to hunger",
        "any": [
          "Agree",
          "Strongly Agree"
        ]
      },
      {
        "id": "H3.3",
        "label": "Academic performance affected by food insecurity",
        "any": [
          "Agree",
          "Strongly Agree"
        ]
      },
      {
        "id": "H3.4",
        "label": "Too tired to study because of lack of food",
        "any": [
          "Agree",
          "Strongly Agree"
        ]
      },
      {
        "id": "H4.1",
        "label": "Often or always stressed about having enough food",
        "any": [
          "Often",
          "Always"
        ]
      },
      {
        "id": "H4.2",
        "label": "Often or always depressed or sad about food situation",
        "any": [
          "Often",
          "Always"
        ]
      },
      {
        "id": "H4.4",
        "label": "Sleep often or always affected",
        "any": [
          "Often",
          "Always"
        ]
      },
      {
        "id": "H5.1",
        "label": "Often or always physically weak from lack of food",
        "any": [
          "Often",
          "Always"
        ]
      },
      {
        "id": "H5.3",
        "label": "Often or always dizzy or faint from not eating",
        "any": [
          "Often",
          "Always"
        ]
      },
      {
        "id": "H6",
        "label": "Rates own health as fair or poor",
        "any": [
          "Fair",
          "Poor"
        ]
      },
      {
        "id": "H7.1",
        "label": "Felt isolated from peers due to food situation",
        "any": [
          "Yes"
        ]
      }
    ],
    "scales": [
      "H3",
      "H4",
      "H5"
    ],
    "diet": {
      "meals": "G1",
      "places": "G2"
    },
    "consequences": {
      "lectures": "H1",
      "coping": "H2",
      "health": "H6",
      "social": "H7"
    },
    "support": {
      "awareness": "I1",
      "accessed": "I2"
    },
    "voices": {
      "recommendations": "J1",
      "programmes": "I2_which"
    },
    "textFields": [
      "J1",
      "I2_which",
      "C2_other",
      "C5_other"
    ]
  },
  "sections": [
    {
      "id": "A",
      "title": "Informed consent",
      "intro": "We are student researchers at Kampala International University conducting a study on food insecurity among students at KIU. Your participation is voluntary, and all information you provide will be kept confidential and used only for academic purposes. You may withdraw at any time without penalty.",
      "questions": [
        {
          "id": "A1",
          "type": "radio",
          "short": "Enrolled undergraduate and consents",
          "text": "Are you currently an enrolled undergraduate student at KIU, and do you consent to participate in this study?",
          "options": [
            "Yes, I consent",
            "No, I do not consent"
          ],
          "required": true,
          "screenOut": {
            "No, I do not consent": "consent"
          }
        },
        {
          "id": "A2",
          "type": "radio",
          "short": "Aged 18 or older",
          "text": "Are you 18 years of age or older?",
          "options": [
            "Yes",
            "No"
          ],
          "required": true,
          "screenOut": {
            "No": "age"
          }
        }
      ]
    },
    {
      "id": "B",
      "title": "Demographic and background information",
      "questions": [
        {
          "id": "CAMPUS",
          "code": "Campus",
          "type": "radio",
          "short": "Campus",
          "text": "Campus",
          "options": [
            "Main Campus (Kansanga, Kampala)",
            "Western Campus (Ishaka, Bushenyi)"
          ],
          "required": true
        },
        {
          "id": "B1",
          "type": "number",
          "short": "Age",
          "text": "Age (in completed years)",
          "min": 18,
          "max": 80,
          "required": true
        },
        {
          "id": "B2",
          "type": "radio",
          "short": "Sex",
          "text": "Sex",
          "options": [
            "Male",
            "Female"
          ],
          "required": true
        },
        {
          "id": "B3",
          "type": "radio",
          "short": "Year of study",
          "text": "Year of study",
          "options": [
            "Year 1",
            "Year 2",
            "Year 3",
            "Year 4",
            "Year 5+"
          ],
          "required": true
        },
        {
          "id": "B4",
          "type": "radio",
          "short": "College / school",
          "text": "Which College or School do you belong to?",
          "dependsOn": "CAMPUS",
          "dependsHint": "Select your campus above to see its colleges and schools.",
          "optionsBy": {
            "Main Campus (Kansanga, Kampala)": [
              "College of Economics and Management",
              "College of Humanities and Social Sciences",
              "College of Education, Open and Distance Learning",
              "School of Law",
              "School of Public Health",
              "School of Mathematics and Computing",
              "School of Natural and Applied Sciences",
              "School of Digital, Distance and E-Learning"
            ],
            "Western Campus (Ishaka, Bushenyi)": [
              "Faculty of Clinical Medicine and Dentistry",
              "Faculty of Biomedical Sciences",
              "School of Allied Health Sciences",
              "School of Nursing Sciences",
              "School of Pharmacy",
              "School of Engineering and Applied Sciences",
              "School of Agriculture Sciences"
            ]
          },
          "options": [
            "College of Economics and Management",
            "College of Humanities and Social Sciences",
            "College of Education, Open and Distance Learning",
            "School of Law",
            "School of Public Health",
            "School of Mathematics and Computing",
            "School of Natural and Applied Sciences",
            "School of Digital, Distance and E-Learning",
            "Faculty of Clinical Medicine and Dentistry",
            "Faculty of Biomedical Sciences",
            "School of Allied Health Sciences",
            "School of Nursing Sciences",
            "School of Pharmacy",
            "School of Engineering and Applied Sciences",
            "School of Agriculture Sciences"
          ],
          "required": true
        },
        {
          "id": "B5",
          "type": "radio",
          "short": "Sponsorship status",
          "text": "Sponsorship status",
          "options": [
            "KIU-sponsored",
            "Privately/self-sponsored"
          ],
          "required": true
        },
        {
          "id": "B6",
          "type": "radio",
          "short": "Residence status",
          "text": "Residence status during academic sessions",
          "options": [
            "Resident (on-campus/university hostel)",
            "Non-resident (off-campus)"
          ],
          "required": true
        },
        {
          "id": "B7",
          "type": "radio",
          "short": "Marital status",
          "text": "Marital status",
          "options": [
            "Single",
            "Married",
            "Other"
          ],
          "required": true
        }
      ]
    },
    {
      "id": "C",
      "title": "Socio-economic determinants of food insecurity",
      "questions": [
        {
          "id": "C1",
          "type": "radio",
          "short": "Monthly income / allowance (UGX)",
          "text": "What is your average monthly income/allowance (UGX)?",
          "options": [
            "Below UGX 50,000",
            "UGX 50,000–100,000",
            "UGX 100,001–200,000",
            "UGX 200,001–300,000",
            "UGX 300,001–500,000",
            "Above UGX 500,000"
          ],
          "required": true
        },
        {
          "id": "C2",
          "type": "radio",
          "short": "Main source of income",
          "text": "What is the main source of this income/allowance?",
          "options": [
            "Family/parents",
            "Guardian/sponsor",
            "Personal employment",
            "Scholarship/bursary",
            "Other (specify)"
          ],
          "other": "Other (specify)",
          "required": true
        },
        {
          "id": "C3",
          "type": "radio",
          "short": "Employment status",
          "text": "What is your employment status?",
          "options": [
            "Employed (part-time)",
            "Employed (full-time)",
            "Unemployed / not working"
          ],
          "required": true
        },
        {
          "id": "C4",
          "type": "radio",
          "short": "Parent / guardian education",
          "text": "What is the highest education level attained by your parent/guardian?",
          "options": [
            "No formal education",
            "Primary",
            "Secondary",
            "Tertiary/University",
            "Postgraduate"
          ],
          "required": true
        },
        {
          "id": "C5",
          "type": "radio",
          "short": "Parent / guardian occupation",
          "text": "What is the main occupation of your parent/guardian?",
          "options": [
            "Formal employment",
            "Business/self-employed",
            "Peasant farming",
            "Unemployed",
            "Other (specify)"
          ],
          "other": "Other (specify)",
          "required": true
        },
        {
          "id": "C6",
          "type": "radio",
          "short": "Household income level",
          "text": "How would you describe your household's monthly income level?",
          "options": [
            "Low",
            "Middle",
            "High",
            "Not sure"
          ],
          "required": true
        },
        {
          "id": "C7",
          "type": "radio",
          "short": "Weekly food spending (UGX)",
          "text": "On average, how much do you spend on food per week?",
          "options": [
            "Below UGX 10,000",
            "UGX 10,001–20,000",
            "UGX 20,001–30,000",
            "UGX 30,001–50,000",
            "Above UGX 50,000"
          ],
          "required": true
        }
      ]
    },
    {
      "id": "D",
      "title": "Food Insecurity Experience Scale (FIES)",
      "intro": "Please answer Yes or No for each statement.",
      "questions": [
        {
          "id": "D",
          "code": "D1–D8",
          "type": "matrix",
          "short": "FIES",
          "text": "FIES items (FAO Food Insecurity Experience Scale)",
          "columns": [
            "Yes",
            "No"
          ],
          "rows": [
            {
              "id": "D1",
              "short": "Worried about not having enough food",
              "text": "During the last 12 months, was there a time when you worried you would not have enough food to eat because of a lack of money or other resources?"
            },
            {
              "id": "D2",
              "short": "Unable to eat healthy and nutritious food",
              "text": "During the last 12 months, was there a time when you were unable to eat healthy and nutritious food because of a lack of money or other resources?"
            },
            {
              "id": "D3",
              "short": "Ate only a few kinds of foods",
              "text": "During the last 12 months, was there a time when you ate only a few kinds of foods because of a lack of money or other resources?"
            },
            {
              "id": "D4",
              "short": "Skipped a meal",
              "text": "During the last 12 months, was there a time when you had to skip a meal because there was not enough money or other resources to get food?"
            },
            {
              "id": "D5",
              "short": "Ate less than you should",
              "text": "During the last 12 months, was there a time when you ate less than you thought you should because of a lack of money or other resources?"
            },
            {
              "id": "D6",
              "short": "Household ran out of food",
              "text": "During the last 12 months, was there a time when your household ran out of food because of a lack of money or other resources?"
            },
            {
              "id": "D7",
              "short": "Hungry but did not eat",
              "text": "During the last 12 months, was there a time when you felt hungry but did not eat because there was not enough money or other resources for food?"
            },
            {
              "id": "D8",
              "short": "Went without eating for a whole day",
              "text": "During the last 12 months, was there a time when you went without eating for a whole day because of a lack of money or other resources?"
            }
          ],
          "required": true
        }
      ]
    },
    {
      "id": "E",
      "title": "24-hour dietary recall",
      "intro": "Think about everything you ate and drank YESTERDAY, from when you woke up to when you went to sleep. Include snacks and drinks. Write 'None' if you had nothing at that time.",
      "questions": [
        {
          "id": "E1",
          "type": "textarea",
          "short": "Early morning",
          "text": "Early morning (on waking)",
          "hint": "List all foods and beverages consumed (or write \"None\").",
          "required": true
        },
        {
          "id": "E2",
          "type": "textarea",
          "short": "Breakfast",
          "text": "Breakfast",
          "hint": "List all foods and beverages consumed (or write \"None\").",
          "required": true
        },
        {
          "id": "E3",
          "type": "textarea",
          "short": "Mid-morning snack",
          "text": "Mid-morning snack",
          "hint": "List all foods and beverages consumed (or write \"None\").",
          "required": true
        },
        {
          "id": "E4",
          "type": "textarea",
          "short": "Lunch",
          "text": "Lunch",
          "hint": "List all foods and beverages consumed (or write \"None\").",
          "required": true
        },
        {
          "id": "E5",
          "type": "textarea",
          "short": "Afternoon snack",
          "text": "Afternoon snack",
          "hint": "List all foods and beverages consumed (or write \"None\").",
          "required": true
        },
        {
          "id": "E6",
          "type": "textarea",
          "short": "Supper / dinner",
          "text": "Supper/Dinner",
          "hint": "List all foods and beverages consumed (or write \"None\").",
          "required": true
        },
        {
          "id": "E7",
          "type": "textarea",
          "short": "Late evening / before bed",
          "text": "Late evening / before bed",
          "hint": "List all foods and beverages consumed (or write \"None\").",
          "required": true
        }
      ]
    },
    {
      "id": "F",
      "title": "Individual Dietary Diversity Score (IDDS)",
      "intro": "Thinking about YESTERDAY (from waking up to sleeping), select every food group you ate or drank from. Condiments, spices, and beverages of negligible nutritional value are not counted.",
      "questions": [
        {
          "id": "F",
          "code": "F1–F10",
          "type": "checkbox",
          "short": "Food groups consumed yesterday",
          "text": "Food Group (FAO Individual Dietary Diversity Score)",
          "hint": "Select if consumed. Leave unselected any group you did not eat or drink from.",
          "options": [
            "Starchy staples (e.g., posho, matooke, rice, bread, potatoes, cassava)",
            "Dark green leafy vegetables (e.g., dodo, nakati, spinach)",
            "Other vitamin A-rich fruits/vegetables (e.g., mango, pumpkin, carrots, papaya)",
            "Other vegetables (e.g., tomatoes, onions, cabbage, eggplant)",
            "Other fruits (e.g., banana, orange, pineapple, jackfruit)",
            "Organ meat (e.g., liver, kidney)",
            "Meat and fish (e.g., beef, chicken, fish, goat)",
            "Eggs",
            "Legumes, nuts and seeds (e.g., beans, groundnuts, peas, simsim)",
            "Milk and milk products (e.g., milk, yogurt, cheese)"
          ],
          "flagPrefix": "F",
          "required": false
        }
      ]
    },
    {
      "id": "G",
      "title": "Dietary factors",
      "questions": [
        {
          "id": "G1",
          "type": "radio",
          "short": "Meals per day",
          "text": "How many meals do you typically eat per day?",
          "options": [
            "1 meal",
            "2 meals",
            "3 meals",
            "More than 3 meals"
          ],
          "required": true
        },
        {
          "id": "G2",
          "type": "checkbox",
          "short": "Where meals are eaten",
          "text": "Where do you usually eat your meals?",
          "hint": "You may select more than one.",
          "options": [
            "University cafeteria",
            "Off-campus restaurant/food vendor",
            "Self-prepared at residence",
            "At friends'/relatives' place",
            "Don't eat regular meals"
          ],
          "required": true
        }
      ]
    },
    {
      "id": "H",
      "title": "Consequences of food insecurity",
      "questions": [
        {
          "id": "H1",
          "type": "radio",
          "short": "Lectures missed (30 days)",
          "text": "In the past 30 days, how many lectures have you missed due to hunger or lack of food?",
          "options": [
            "None",
            "1–2",
            "3–5",
            "More than 5"
          ],
          "required": true
        },
        {
          "id": "H2",
          "type": "checkbox",
          "short": "Coping strategies (30 days)",
          "text": "In the past 30 days, which of the following coping strategies have you used when food was not available?",
          "hint": "Select all that apply.",
          "options": [
            "Borrowed money to buy food",
            "Borrowed/asked others for food",
            "Reduced number/size of meals",
            "Took on casual labor for food/money",
            "Sold personal possessions",
            "Relied on a transactional relationship for food or money",
            "Relied on student union/religious group/organization support",
            "None of the above"
          ],
          "exclusive": "None of the above",
          "required": true
        },
        {
          "id": "H3",
          "type": "matrix",
          "short": "Academic impact",
          "text": "Academic Impact",
          "prompt": "In the past 30 days:",
          "columns": [
            "Strongly Disagree",
            "Disagree",
            "Neutral",
            "Agree",
            "Strongly Agree"
          ],
          "rows": [
            {
              "id": "H3.1",
              "short": "Difficulty concentrating",
              "text": "I have had difficulty concentrating in class due to hunger"
            },
            {
              "id": "H3.2",
              "short": "Missed classes, no food",
              "text": "I have missed classes because I had no food to eat"
            },
            {
              "id": "H3.3",
              "short": "Academic performance affected",
              "text": "My academic performance has been affected by food insecurity"
            },
            {
              "id": "H3.4",
              "short": "Too tired to study",
              "text": "I have been too tired to study because of lack of food"
            },
            {
              "id": "H3.5",
              "short": "Skipped library / study sessions",
              "text": "I have skipped library or study sessions due to hunger"
            }
          ],
          "required": true
        },
        {
          "id": "H4",
          "type": "matrix",
          "short": "Mental health impact",
          "text": "Mental Health Impact",
          "prompt": "In the past 30 days:",
          "columns": [
            "Never",
            "Rarely",
            "Sometimes",
            "Often",
            "Always"
          ],
          "rows": [
            {
              "id": "H4.1",
              "short": "Stressed about food",
              "text": "I have felt stressed about having enough food"
            },
            {
              "id": "H4.2",
              "short": "Depressed or sad",
              "text": "I have felt depressed or sad about my food situation"
            },
            {
              "id": "H4.3",
              "short": "Embarrassed",
              "text": "I have felt embarrassed about my food situation"
            },
            {
              "id": "H4.4",
              "short": "Sleep affected",
              "text": "Food insecurity has affected my sleep"
            }
          ],
          "required": true
        },
        {
          "id": "H5",
          "type": "matrix",
          "short": "Physical health impact",
          "text": "Physical Health Impact",
          "prompt": "In the past 30 days:",
          "columns": [
            "Never",
            "Rarely",
            "Sometimes",
            "Often",
            "Always"
          ],
          "rows": [
            {
              "id": "H5.1",
              "short": "Physically weak",
              "text": "I have felt physically weak due to lack of food"
            },
            {
              "id": "H5.2",
              "short": "Headaches",
              "text": "I have experienced headaches due to hunger"
            },
            {
              "id": "H5.3",
              "short": "Dizzy or faint",
              "text": "I have felt dizzy or faint from not eating enough"
            },
            {
              "id": "H5.4",
              "short": "Sick more often",
              "text": "I have fallen sick more often than usual"
            }
          ],
          "required": true
        },
        {
          "id": "H6",
          "type": "radio",
          "short": "Overall health rating",
          "text": "How would you rate your overall health?",
          "options": [
            "Excellent",
            "Very good",
            "Good",
            "Fair",
            "Poor"
          ],
          "required": true
        },
        {
          "id": "H7",
          "type": "matrix",
          "short": "Social impact",
          "text": "Social Impact",
          "prompt": "In the past 30 days:",
          "columns": [
            "Yes",
            "No"
          ],
          "rows": [
            {
              "id": "H7.1",
              "short": "Isolated from peers",
              "text": "I have felt isolated from peers due to my food situation"
            },
            {
              "id": "H7.2",
              "short": "Friendships affected",
              "text": "My relationships with friends have been affected"
            },
            {
              "id": "H7.3",
              "short": "Ashamed to ask for help",
              "text": "I have felt ashamed to ask for help with food"
            }
          ],
          "required": true
        }
      ]
    },
    {
      "id": "I",
      "title": "Institutional support and awareness",
      "questions": [
        {
          "id": "I1",
          "type": "matrix",
          "short": "Food support programs available",
          "text": "Does your university have any of the following food support programs?",
          "columns": [
            "Yes",
            "No",
            "Don't Know"
          ],
          "rows": [
            {
              "id": "I1.1",
              "short": "Subsidized cafeteria",
              "text": "Subsidized cafeteria/dining hall"
            },
            {
              "id": "I1.2",
              "short": "Food vouchers / meal plans",
              "text": "Food vouchers or meal plans"
            },
            {
              "id": "I1.3",
              "short": "Emergency food assistance",
              "text": "Emergency food assistance"
            },
            {
              "id": "I1.4",
              "short": "Food bank",
              "text": "Food bank"
            },
            {
              "id": "I1.5",
              "short": "Bursary / welfare fund for food",
              "text": "Bursary/welfare fund for food"
            }
          ],
          "required": true
        },
        {
          "id": "I2",
          "type": "radio",
          "short": "Accessed food support",
          "text": "Have you ever accessed any food support programs at your university?",
          "options": [
            "Yes",
            "No",
            "Not available"
          ],
          "required": true,
          "followUp": {
            "id": "I2_which",
            "when": "Yes",
            "short": "Which program(s)",
            "text": "Which one(s)?",
            "required": true
          }
        }
      ]
    },
    {
      "id": "J",
      "title": "Recommendations and suggestions",
      "questions": [
        {
          "id": "J1",
          "type": "textarea",
          "short": "Recommended interventions",
          "text": "What interventions do you think would be most helpful to address food insecurity among students?",
          "required": false
        }
      ]
    }
  ]
};

var RESPONSES_TAB = "Responses";
var SUMMARY_TAB = "Summary";
var CODEBOOK_TAB = "Codebook";
var TIMEZONE = "Africa/Kampala";
var NOTES_HEADER = "Notes";
var ID_HEADER = "Response ID";
var NUMBER_HEADER = "Questionnaire No.";
var DASHBOARD_KEY_PROP = "DASHBOARD_KEY";
var DASHBOARD_PUBLIC_PROP = "DASHBOARD_PUBLIC";
var PUBLIC_CACHE_KEY = "dashboard-public";
var PUBLIC_CACHE_SECONDS = 60;

function getSpreadsheet() {
  if (SPREADSHEET_ID) return SpreadsheetApp.openById(SPREADSHEET_ID);
  return SpreadsheetApp.getActiveSpreadsheet();
}

function allQuestions() {
  var list = [];
  STUDY.sections.forEach(function (section) {
    section.questions.forEach(function (question) {
      list.push(question);
    });
  });
  return list;
}

function shortOption(label) {
  return String(label).split(" (e.g.")[0];
}

function asList(value) {
  if (Array.isArray(value)) return value;
  if (value === undefined || value === null || value === "") return [];
  return [String(value)];
}

function clean(value) {
  var text = Array.isArray(value) ? value.join("; ") : String(value === undefined || value === null ? "" : value);
  text = text.replace(/\s+$/g, "");
  // Stops spreadsheet formula injection from free-text answers.
  return /^[=+\-@]/.test(text) ? "'" + text : text;
}

function scoreBand(score, categories) {
  for (var i = 0; i < categories.length; i++) {
    if (score <= categories[i].max) return categories[i].label;
  }
  return "";
}

function fiesScore(data) {
  var fies = STUDY.scoring.fies;
  return fies.items.reduce(function (total, id) {
    return total + (data[id] === fies.yes ? 1 : 0);
  }, 0);
}

function iddsScore(data) {
  return asList(data[STUDY.scoring.idds.question]).length;
}

/** Column definitions: header, question text for the codebook, coding note, and how to read the value. */
function columns() {
  var cols = [
    { header: NUMBER_HEADER, text: "Sequential questionnaire number assigned on receipt", coding: "KIU-0001, KIU-0002, …", meta: "number" },
    { header: ID_HEADER, text: "Unique ID generated by the respondent's browser; used to drop duplicate submissions", coding: "Text", meta: "responseId" },
    { header: "Submitted", text: "Date and time the response was received (Africa/Kampala)", coding: "Date/time", meta: "submitted" },
    { header: "Minutes to complete", text: "Time between opening the questionnaire and submitting it", coding: "Minutes", meta: "duration" },
    { header: "Form version", text: "Version of the questionnaire definition", coding: "Text", meta: "version" }
  ];

  allQuestions().forEach(function (q) {
    var code = q.code || q.id;
    if (q.type === "matrix") {
      q.rows.forEach(function (row) {
        cols.push({
          header: row.id + " · " + row.short,
          text: (q.prompt ? q.prompt + " " : "") + row.text,
          coding: q.columns.join(" / "),
          key: row.id
        });
      });
      return;
    }
    if (q.type === "checkbox") {
      cols.push({ header: code + " · " + q.short, text: q.text, coding: "Selected options, separated by ;", key: q.id, list: true });
      q.options.forEach(function (option, index) {
        var flagId = (q.flagPrefix || q.id + ".") + (index + 1);
        cols.push({ header: flagId + " · " + shortOption(option), text: q.text + " — " + option, coding: "1 = selected, 0 = not selected", key: q.id, flag: option });
      });
      return;
    }
    cols.push({
      header: code === q.short ? code : code + " · " + q.short,
      text: q.text,
      coding: q.optionsBy
        ? Object.keys(q.optionsBy)
            .map(function (parent) {
              return parent + ": " + q.optionsBy[parent].join(" / ");
            })
            .join("; ")
        : q.options
        ? q.options.join(" / ")
        : q.type === "number"
        ? "Number"
        : "Free text",
      key: q.id,
      numeric: q.type === "number"
    });
    if (q.other) {
      cols.push({ header: code + " · Other (specify)", text: q.text + " — Other (specify)", coding: "Free text", key: q.id + "_other" });
    }
    if (q.followUp) {
      cols.push({ header: code + " · " + q.followUp.short, text: q.text + " — " + q.followUp.text, coding: "Free text (asked if " + q.followUp.when + ")", key: q.followUp.id });
    }
  });

  cols.push({ header: "FIES raw score", text: "Sum of 'Yes' answers to D1–D8", coding: "0–8", computed: "fies" });
  cols.push({ header: "FIES category", text: "FIES raw score band", coding: "0 Food secure; 1–3 Mildly; 4–6 Moderately; 7–8 Severely food insecure", computed: "fiesBand" });
  cols.push({ header: "IDDS score", text: "Count of food groups selected in Section F", coding: "0–10", computed: "idds" });
  cols.push({ header: "IDDS class", text: "IDDS band", coding: "Low < 4; Medium 4–5; High ≥ 6", computed: "iddsBand" });
  cols.push({ header: NOTES_HEADER, text: "Research team notes (not part of the questionnaire)", coding: "Free text" });
  return cols;
}

function cellValue(col, data, number, now) {
  if (col.meta === "number") return "KIU-" + ("000" + number).slice(-4);
  if (col.meta === "responseId") return clean(data.responseId);
  if (col.meta === "submitted") return now;
  if (col.meta === "version") return clean(data.formVersion);
  if (col.meta === "duration") {
    var started = Date.parse(data.startedAt);
    return isNaN(started) ? "" : Math.max(0, Math.round(((now.getTime() - started) / 60000) * 10) / 10);
  }
  if (col.computed === "fies") return fiesScore(data);
  if (col.computed === "fiesBand") return scoreBand(fiesScore(data), STUDY.scoring.fies.categories);
  if (col.computed === "idds") return iddsScore(data);
  if (col.computed === "iddsBand") return scoreBand(iddsScore(data), STUDY.scoring.idds.categories);
  if (col.flag) return asList(data[col.key]).indexOf(col.flag) === -1 ? 0 : 1;
  if (col.key) {
    var value = data[col.key];
    if (col.list) return clean(asList(value));
    if (col.numeric && value !== "" && value !== undefined && !isNaN(Number(value))) return Number(value);
    return clean(value);
  }
  return "";
}

function doGet(e) {
  var params = (e && e.parameter) || {};
  if (params.view === "dashboard") return jsonOutput(dashboardPayload(params));
  return jsonOutput({ ok: true, study: STUDY.id, version: STUDY.version });
}

/**
 * Live dashboard feed. The research team (correct key) receives anonymised records, with no IDs or 24-hour recall,
 * so the page can filter them. Everyone else gets nothing until the team opens the dashboard to the public; then
 * they receive aggregated results only, with groups under analysis.publicMinCell suppressed.
 */
function dashboardPayload(params) {
  var props = PropertiesService.getScriptProperties();
  var key = props.getProperty(DASHBOARD_KEY_PROP);
  var isTeam = Boolean(key) && params.key === key;
  var cache = CacheService.getScriptCache();

  if (isTeam && (params.public === "on" || params.public === "off")) {
    props.setProperty(DASHBOARD_PUBLIC_PROP, params.public);
    cache.remove(PUBLIC_CACHE_KEY);
  }
  var isPublic = props.getProperty(DASHBOARD_PUBLIC_PROP) === "on";
  var generatedAt = new Date().toISOString();

  if (isTeam) {
    var team = readRecords(true);
    return { ok: true, mode: "team", public: isPublic, generatedAt: generatedAt, excluded: team.excluded, records: team.records };
  }
  if (!isPublic) return { ok: false, error: params.key ? "wrong-key" : "locked" };

  var cached = cache.get(PUBLIC_CACHE_KEY);
  var payload = cached ? JSON.parse(cached) : null;
  if (!payload) {
    var data = readRecords(false);
    payload = {
      ok: true,
      mode: "public",
      public: true,
      generatedAt: generatedAt,
      excluded: data.excluded,
      analysis: StudyAnalytics.analyse(data.records, STUDY, { minCell: STUDY.analysis.publicMinCell, includeText: false })
    };
    cache.put(PUBLIC_CACHE_KEY, JSON.stringify(payload), PUBLIC_CACHE_SECONDS);
  }
  payload.keyRejected = Boolean(params.key);
  return payload;
}

/** Reads Responses back into records keyed by question ID. Rows whose Notes start with "exclude" are left out. */
function readRecords(includeText) {
  var sheet = getSpreadsheet().getSheetByName(RESPONSES_TAB);
  if (!sheet || sheet.getLastRow() < 2) return { records: [], excluded: 0 };

  var values = sheet.getRange(1, 1, sheet.getLastRow(), sheet.getLastColumn()).getValues();
  var headers = values[0].map(function (value) {
    return String(value || "").trim();
  });
  var byHeader = {};
  columns().forEach(function (col) {
    byHeader[col.header] = col;
  });

  var textKeys = {};
  allQuestions().forEach(function (q) {
    if (q.type === "textarea" || q.type === "text") textKeys[q.id] = true;
    if (q.other) textKeys[q.id + "_other"] = true;
    if (q.followUp) textKeys[q.followUp.id] = true;
  });
  var allowedText = {};
  if (includeText) {
    STUDY.analysis.textFields.forEach(function (id) {
      allowedText[id] = true;
    });
  }

  var notesIndex = headers.indexOf(NOTES_HEADER);
  var excluded = 0;
  var records = [];
  for (var r = 1; r < values.length; r++) {
    var row = values[r];
    if (notesIndex !== -1 && /^\s*exclude/i.test(String(row[notesIndex] || ""))) {
      excluded++;
      continue;
    }
    var record = {};
    var hasAnswers = false;
    headers.forEach(function (header, c) {
      var col = byHeader[header];
      var value = row[c];
      if (!col || col.flag || col.computed) return;
      if (col.meta === "submitted") {
        if (value instanceof Date) record.submitted = Utilities.formatDate(value, TIMEZONE, "yyyy-MM-dd'T'HH:mm");
        return;
      }
      if (col.meta === "duration") {
        if (value !== "" && !isNaN(Number(value))) record.minutes = Number(value);
        return;
      }
      if (!col.key) return;
      if (textKeys[col.key] && !allowedText[col.key]) return;
      if (value === "" || value === null) return;
      hasAnswers = true;
      if (col.list) record[col.key] = String(value).split(/;\s*/);
      else if (col.numeric) record[col.key] = Number(value);
      else record[col.key] = String(value);
    });
    if (hasAnswers) records.push(record);
  }
  return { records: records, excluded: excluded };
}

/** Run once from the editor: creates the dashboard access key (if missing) and prints it in the execution log. */
function showDashboardKey() {
  var props = PropertiesService.getScriptProperties();
  var key = props.getProperty(DASHBOARD_KEY_PROP);
  if (!key) {
    key = Utilities.getUuid().replace(/-/g, "").slice(0, 12);
    props.setProperty(DASHBOARD_KEY_PROP, key);
  }
  Logger.log("Dashboard access key: " + key + " (public: " + (props.getProperty(DASHBOARD_PUBLIC_PROP) === "on") + ")");
  return key;
}

/** Replaces the access key; anyone holding the old key loses access. */
function resetDashboardKey() {
  PropertiesService.getScriptProperties().deleteProperty(DASHBOARD_KEY_PROP);
  return showDashboardKey();
}

function openDashboardToPublic() {
  PropertiesService.getScriptProperties().setProperty(DASHBOARD_PUBLIC_PROP, "on");
  CacheService.getScriptCache().remove(PUBLIC_CACHE_KEY);
}

function closeDashboardToPublic() {
  PropertiesService.getScriptProperties().setProperty(DASHBOARD_PUBLIC_PROP, "off");
  CacheService.getScriptCache().remove(PUBLIC_CACHE_KEY);
}

function doPost(e) {
  if (!e || !e.postData || !e.postData.contents) return jsonOutput({ ok: false, error: "Empty body" });

  var data;
  try {
    data = JSON.parse(e.postData.contents);
  } catch (error) {
    return jsonOutput({ ok: false, error: "Invalid JSON" });
  }
  if (data._gotcha) return jsonOutput({ ok: true, ignored: true });
  if (!data.responseId) return jsonOutput({ ok: false, error: "Missing responseId" });
  if (data[STUDY.consent.question] !== STUDY.consent.yes || data[STUDY.consent.ageQuestion] !== STUDY.consent.ageYes) {
    return jsonOutput({ ok: false, error: "Not eligible" });
  }

  var lock = LockService.getScriptLock();
  lock.waitLock(20000);
  try {
    var sheet = ensureResponsesSheet(getSpreadsheet());
    var headers = readHeaders(sheet);
    var idCol = headers.indexOf(ID_HEADER) + 1;
    if (idCol > 0 && sheet.getLastRow() > 1) {
      var found = sheet
        .getRange(2, idCol, sheet.getLastRow() - 1, 1)
        .createTextFinder(String(data.responseId))
        .matchEntireCell(true)
        .findNext();
      if (found) return jsonOutput({ ok: true, duplicate: true });
    }

    var byHeader = {};
    var now = new Date();
    var number = sheet.getLastRow();
    columns().forEach(function (col) {
      byHeader[col.header] = cellValue(col, data, number, now);
    });
    sheet.appendRow(
      headers.map(function (header) {
        return Object.prototype.hasOwnProperty.call(byHeader, header) ? byHeader[header] : "";
      })
    );
    return jsonOutput({ ok: true });
  } catch (error) {
    return jsonOutput({ ok: false, error: String(error) });
  } finally {
    lock.releaseLock();
  }
}

function readHeaders(sheet) {
  var lastColumn = sheet.getLastColumn();
  if (lastColumn < 1) return [];
  return sheet
    .getRange(1, 1, 1, lastColumn)
    .getValues()[0]
    .map(function (value) {
      return String(value || "").trim();
    });
}

function columnLetter(index) {
  var letters = "";
  while (index > 0) {
    var remainder = (index - 1) % 26;
    letters = String.fromCharCode(65 + remainder) + letters;
    index = Math.floor((index - 1) / 26);
  }
  return letters;
}

/** Creates the Responses tab or adds any new columns before Notes, without moving existing data. */
function ensureResponsesSheet(spreadsheet) {
  var sheet = spreadsheet.getSheetByName(RESPONSES_TAB) || spreadsheet.insertSheet(RESPONSES_TAB, 0);
  var wanted = columns().map(function (col) {
    return col.header;
  });
  var existing = readHeaders(sheet);
  var hasHeaders = existing.some(function (header) {
    return header !== "";
  });

  if (!hasHeaders) {
    sheet.getRange(1, 1, 1, wanted.length).setValues([wanted]);
    styleResponses(sheet, wanted.length);
    return sheet;
  }

  var missing = wanted.filter(function (header) {
    return existing.indexOf(header) === -1;
  });
  if (missing.length) {
    var notesCol = existing.indexOf(NOTES_HEADER) + 1;
    if (notesCol > 0) {
      sheet.insertColumnsBefore(notesCol, missing.length);
      sheet.getRange(1, notesCol, 1, missing.length).setValues([missing]);
    } else {
      sheet.getRange(1, existing.length + 1, 1, missing.length).setValues([missing]);
    }
    styleResponses(sheet, readHeaders(sheet).length);
  }
  return sheet;
}

function styleResponses(sheet, width) {
  var header = sheet.getRange(1, 1, 1, width);
  header.setFontWeight("bold").setBackground("#f6c33c").setFontColor("#000000").setWrap(true).setVerticalAlignment("top");
  sheet.setFrozenRows(1);
  sheet.setFrozenColumns(2);
  sheet.setRowHeight(1, 54);
  sheet.setColumnWidths(1, width, 150);
}

function setupWorkbook() {
  var spreadsheet = getSpreadsheet();
  spreadsheet.setSpreadsheetTimeZone(TIMEZONE);
  var sheet = ensureResponsesSheet(spreadsheet);
  writeCodebook(spreadsheet);
  writeSummary(spreadsheet, readHeaders(sheet));
  showDashboardKey();
}

function writeCodebook(spreadsheet) {
  var sheet = spreadsheet.getSheetByName(CODEBOOK_TAB) || spreadsheet.insertSheet(CODEBOOK_TAB);
  sheet.clear();
  var rows = [["Column", "Question (verbatim)", "Response options / coding"]];
  columns().forEach(function (col) {
    rows.push([col.header, col.text || "", col.coding || ""]);
  });
  sheet.getRange(1, 1, rows.length, 3).setValues(rows).setWrap(true).setVerticalAlignment("top");
  sheet.getRange(1, 1, 1, 3).setFontWeight("bold").setBackground("#f6c33c");
  sheet.setFrozenRows(1);
  sheet.setColumnWidth(1, 260);
  sheet.setColumnWidth(2, 520);
  sheet.setColumnWidth(3, 320);
}

function writeSummary(spreadsheet, headers) {
  var sheet = spreadsheet.getSheetByName(SUMMARY_TAB) || spreadsheet.insertSheet(SUMMARY_TAB);
  sheet.clear();

  function col(header) {
    var index = headers.indexOf(header) + 1;
    return index > 0 ? "'" + RESPONSES_TAB + "'!" + columnLetter(index) + "2:" + columnLetter(index) : null;
  }
  var idRange = col(ID_HEADER);
  var total = "COUNTA(" + idRange + ")";
  var campusRange = col("Campus");
  var fiesBand = col("FIES category");
  var iddsBand = col("IDDS class");

  var rows = [
    [STUDY.institution, ""],
    ["Food insecurity study — live summary", ""],
    ["", ""],
    ["Total responses", "=" + total],
    ["Mean FIES raw score", "=IFERROR(ROUND(AVERAGE(" + col("FIES raw score") + "),2),\"\")"],
    ["Mean IDDS score", "=IFERROR(ROUND(AVERAGE(" + col("IDDS score") + "),2),\"\")"],
    ["Median minutes to complete", "=IFERROR(MEDIAN(" + col("Minutes to complete") + "),\"\")"],
    ["", ""],
    ["Campus", "Responses"]
  ];
  var campusQuestion = allQuestions().filter(function (q) {
    return q.id === "CAMPUS";
  })[0];
  campusQuestion.options.forEach(function (option) {
    rows.push([option, "=COUNTIF(" + campusRange + ",\"" + option + "\")"]);
  });
  rows.push(["", ""], ["FIES category", "Responses"]);
  STUDY.scoring.fies.categories.forEach(function (band) {
    rows.push([band.label, "=COUNTIF(" + fiesBand + ",\"" + band.label + "\")"]);
  });
  rows.push(["", ""], ["IDDS class", "Responses"]);
  STUDY.scoring.idds.categories.forEach(function (band) {
    rows.push([band.label, "=COUNTIF(" + iddsBand + ",\"" + band.label + "\")"]);
  });

  sheet.getRange(1, 1, rows.length, 2).setValues(rows);
  sheet.getRange("A1").setFontWeight("bold").setFontSize(14);
  sheet.getRange("A2").setFontStyle("italic");
  rows.forEach(function (row, index) {
    if (row[1] === "Responses") sheet.getRange(index + 1, 1, 1, 2).setFontWeight("bold").setBackground("#f6c33c");
  });
  sheet.setColumnWidth(1, 300);
  sheet.setColumnWidth(2, 140);
}

function jsonOutput(payload) {
  return ContentService.createTextOutput(JSON.stringify(payload)).setMimeType(ContentService.MimeType.JSON);
}

// Analysis engine for research dashboards. Runs in the browser (js/research-dashboard.js) and is inlined into the
// study's Google Apps Script (scripts/lib/research/apps-script.js), so it must stay dependency-free ES5.
var StudyAnalytics = (function () {
  var Z = 1.96;
  var STOPWORDS = (
    "about also because been being better could does doing done each every food foods from give given good have " +
    "help into just like make many more most much need needs only other people provide providing should some " +
    "student students such than that their them then there these they this those through university very well " +
    "were what when where which while will with would your kiu kampala international able want things thing " +
    "start create introduce allow lower think"
  ).split(" ");

  function round(value, places) {
    var factor = Math.pow(10, places);
    return Math.round(value * factor) / factor;
  }

  function pct(count, n) {
    return n ? round((count / n) * 100, 1) : null;
  }

  function mean(values) {
    var list = values.filter(function (v) {
      return typeof v === "number" && !isNaN(v);
    });
    if (!list.length) return null;
    return round(
      list.reduce(function (a, b) {
        return a + b;
      }, 0) / list.length,
      2
    );
  }

  function median(values) {
    var list = values
      .filter(function (v) {
        return typeof v === "number" && !isNaN(v);
      })
      .sort(function (a, b) {
        return a - b;
      });
    if (!list.length) return null;
    var mid = Math.floor(list.length / 2);
    return list.length % 2 ? list[mid] : round((list[mid - 1] + list[mid]) / 2, 1);
  }

  function asList(value) {
    if (Array.isArray(value)) return value;
    if (value === undefined || value === null || value === "") return [];
    return String(value).split(/;\s*/);
  }

  function has(value) {
    return value !== undefined && value !== null && value !== "";
  }

  /** Proportion with a Wilson 95% confidence interval. */
  function proportion(count, n) {
    if (!n) return { count: 0, n: 0, pct: null, lo: null, hi: null };
    var p = count / n;
    var z2 = Z * Z;
    var denom = 1 + z2 / n;
    var centre = (p + z2 / (2 * n)) / denom;
    var half = (Z * Math.sqrt((p * (1 - p)) / n + z2 / (4 * n * n))) / denom;
    return {
      count: count,
      n: n,
      pct: pct(count, n),
      lo: round(Math.max(0, centre - half) * 100, 1),
      hi: round(Math.min(1, centre + half) * 100, 1)
    };
  }

  function lnGamma(x) {
    var c = [76.18009172947146, -86.50532032941677, 24.01409824083091, -1.231739572450155, 0.1208650973866179e-2, -0.5395239384953e-5];
    var y = x;
    var tmp = x + 5.5;
    tmp -= (x + 0.5) * Math.log(tmp);
    var series = 1.000000000190015;
    for (var j = 0; j < 6; j++) series += c[j] / ++y;
    return -tmp + Math.log((2.5066282746310005 * series) / x);
  }

  /** Upper regularised incomplete gamma Q(a, x), used for chi-square p-values. */
  function gammaQ(a, x) {
    if (x <= 0) return 1;
    var front = Math.exp(-x + a * Math.log(x) - lnGamma(a));
    if (x < a + 1) {
      var ap = a;
      var sum = 1 / a;
      var del = sum;
      for (var n = 0; n < 500; n++) {
        ap += 1;
        del *= x / ap;
        sum += del;
        if (Math.abs(del) < Math.abs(sum) * 1e-12) break;
      }
      return Math.max(0, 1 - sum * front);
    }
    var tiny = 1e-300;
    var b = x + 1 - a;
    var c = 1 / tiny;
    var d = 1 / b;
    var h = d;
    for (var i = 1; i < 500; i++) {
      var an = -i * (i - a);
      b += 2;
      d = an * d + b;
      if (Math.abs(d) < tiny) d = tiny;
      c = b + an / c;
      if (Math.abs(c) < tiny) c = tiny;
      d = 1 / d;
      var step = d * c;
      h *= step;
      if (Math.abs(step - 1) < 1e-12) break;
    }
    return Math.min(1, front * h);
  }

  /** Pearson chi-square test of independence for a table of [rows][columns] counts. */
  function chiSquare(table) {
    var rows = table.filter(function (row) {
      return row[0] + row[1] > 0;
    });
    if (rows.length < 2) return null;
    var colTotals = [0, 0];
    var total = 0;
    rows.forEach(function (row) {
      colTotals[0] += row[0];
      colTotals[1] += row[1];
      total += row[0] + row[1];
    });
    if (!colTotals[0] || !colTotals[1]) return null;
    var stat = 0;
    var lowExpected = false;
    rows.forEach(function (row) {
      var rowTotal = row[0] + row[1];
      for (var j = 0; j < 2; j++) {
        var expected = (rowTotal * colTotals[j]) / total;
        if (expected < 5) lowExpected = true;
        stat += Math.pow(row[j] - expected, 2) / expected;
      }
    });
    var df = rows.length - 1;
    return { stat: round(stat, 2), df: df, p: round(gammaQ(df / 2, stat / 2), 4), lowExpected: lowExpected };
  }

  function questionMap(study) {
    var map = {};
    study.sections.forEach(function (section) {
      section.questions.forEach(function (q) {
        map[q.id] = q;
        if (q.type === "matrix") {
          q.rows.forEach(function (row) {
            map[row.id] = { id: row.id, short: row.short, text: row.text, type: "radio", options: q.columns, parent: q.id };
          });
        }
        if (q.followUp) map[q.followUp.id] = { id: q.followUp.id, short: q.followUp.short, text: q.followUp.text, type: "text" };
      });
    });
    var bands = (study.analysis && study.analysis.ageBands) || [];
    map.AGE_BAND = {
      id: "AGE_BAND",
      short: "Age group",
      text: "Age group (from B1)",
      type: "radio",
      options: bands.map(function (band) {
        return band.label;
      })
    };
    return map;
  }

  function band(score, categories) {
    for (var i = 0; i < categories.length; i++) {
      if (score <= categories[i].max) return categories[i].label;
    }
    return "";
  }

  function ageBand(age, bands) {
    var value = Number(age);
    if (!has(age) || isNaN(value)) return "";
    return band(value, bands);
  }

  function isFast(record, study) {
    var limit = study.analysis.fastMinutes;
    return typeof record.minutes === "number" && record.minutes < limit;
  }

  /** Adds derived scores without mutating the source records. */
  function prepare(records, study) {
    var fies = study.scoring.fies;
    var idds = study.scoring.idds;
    var moderateMin = fies.categories[1].max + 1;
    var severeMin = fies.categories[2].max + 1;
    var bands = study.analysis.ageBands;
    return records.map(function (source) {
      var r = {};
      for (var key in source) r[key] = source[key];
      r._fies = fies.items.reduce(function (total, id) {
        return total + (r[id] === fies.yes ? 1 : 0);
      }, 0);
      r._band = band(r._fies, fies.categories);
      r._insecure = r._fies >= moderateMin;
      r._severe = r._fies >= severeMin;
      r._idds = asList(r[idds.question]).length;
      r._iddsBand = band(r._idds, idds.categories);
      r.AGE_BAND = ageBand(r.B1, bands);
      return r;
    });
  }

  function filter(records, filters, study, options) {
    var bands = study.analysis.ageBands;
    return records.filter(function (r) {
      for (var id in filters) {
        if (!filters[id]) continue;
        var value = id === "AGE_BAND" ? ageBand(r.B1, bands) : r[id];
        if (value !== filters[id]) return false;
      }
      return !(options && options.excludeFast && isFast(r, study));
    });
  }

  function count(records, test) {
    return records.filter(test).length;
  }

  function suppress(item, minCell) {
    if (minCell && item.n > 0 && item.n < minCell) {
      item.suppressed = true;
      ["count", "pct", "lo", "hi", "mean", "any", "insecure", "meanFies"].forEach(function (key) {
        if (key in item) item[key] = null;
      });
      if (item.parts) item.parts = [];
    }
    return item;
  }

  /** Distribution of a single-choice answer over its options. */
  function dist(records, key, options, minCell) {
    var base = records.filter(function (r) {
      return has(r[key]);
    });
    var n = base.length;
    var items = options.map(function (option) {
      var c = count(base, function (r) {
        return r[key] === option;
      });
      return { label: option, count: c, pct: pct(c, n) };
    });
    if (minCell && n > 0 && n < minCell) {
      items.forEach(function (item) {
        item.count = null;
        item.pct = null;
      });
    }
    return { n: n, items: items };
  }

  /** Share of respondents selecting each option of a multi-select question. */
  function multi(records, key, options, includeBlank) {
    var base = includeBlank
      ? records
      : records.filter(function (r) {
          return asList(r[key]).length > 0;
        });
    var n = base.length;
    return {
      n: n,
      items: options.map(function (option) {
        var c = count(base, function (r) {
          return asList(r[key]).indexOf(option) !== -1;
        });
        return { label: option, count: c, pct: pct(c, n) };
      })
    };
  }

  function histogram(records, key, min, max) {
    var items = [];
    for (var value = min; value <= max; value++) {
      var v = value;
      items.push({
        label: String(v),
        count: count(records, function (r) {
          return r[key] === v;
        })
      });
    }
    return { n: records.length, items: items };
  }

  /** Answer distribution within each food-insecurity band. */
  function byBand(records, key, options, bandLabels, minCell) {
    return bandLabels.map(function (label) {
      var subset = records.filter(function (r) {
        return r._band === label;
      });
      var d = dist(subset, key, options, 0);
      return suppress({ label: label, n: d.n, parts: d.items }, minCell);
    });
  }

  function meanByBand(records, key, bandLabels, minCell) {
    return bandLabels.map(function (label) {
      var subset = records.filter(function (r) {
        return r._band === label;
      });
      return suppress(
        {
          label: label,
          n: subset.length,
          mean: mean(
            subset.map(function (r) {
              return r[key];
            })
          )
        },
        minCell
      );
    });
  }

  /** Moderate-or-severe food insecurity prevalence in each subgroup of a determinant, with a chi-square test. */
  function determinant(records, q, minCell) {
    var rows = q.options.map(function (option) {
      var subset = records.filter(function (r) {
        return r[q.id] === option;
      });
      var insecure = count(subset, function (r) {
        return r._insecure;
      });
      var row = proportion(insecure, subset.length);
      row.label = option;
      row.insecure = insecure;
      row.any = pct(
        count(subset, function (r) {
          return r._fies > 0;
        }),
        subset.length
      );
      row.meanFies = mean(
        subset.map(function (r) {
          return r._fies;
        })
      );
      return row;
    });
    var test = chiSquare(
      rows.map(function (row) {
        return [row.insecure, row.n - row.insecure];
      })
    );
    return {
      id: q.id,
      label: q.short,
      test: test,
      rows: rows.map(function (row) {
        return suppress(row, minCell);
      })
    };
  }

  function matches(value, rule) {
    if (!has(value)) return false;
    if (rule.any) return rule.any.indexOf(value) !== -1;
    if (rule.not) return rule.not.indexOf(value) === -1;
    return false;
  }

  /** An outcome's prevalence among moderately/severely food-insecure students versus everyone else. */
  function outcome(records, rule, minCell) {
    var base = records.filter(function (r) {
      return has(r[rule.id]);
    });
    function share(subset) {
      return proportion(
        count(subset, function (r) {
          return matches(r[rule.id], rule);
        }),
        subset.length
      );
    }
    var insecure = share(
      base.filter(function (r) {
        return r._insecure;
      })
    );
    var others = share(
      base.filter(function (r) {
        return !r._insecure;
      })
    );
    var test = chiSquare([
      [insecure.count, insecure.n - insecure.count],
      [others.count, others.n - others.count]
    ]);
    var result = {
      id: rule.id,
      label: rule.label,
      all: share(base),
      insecure: suppress(insecure, minCell),
      others: suppress(others, minCell),
      ratio: null,
      test: test
    };
    if (!insecure.suppressed && !others.suppressed && others.pct) result.ratio = round(insecure.pct / others.pct, 2);
    return result;
  }

  /** Likert grid: per-item distribution plus a 1–5 index compared across food-insecurity bands. */
  function scale(records, q, bandLabels, minCell) {
    var items = q.rows.map(function (row) {
      var d = dist(records, row.id, q.columns, 0);
      var scores = records
        .filter(function (r) {
          return has(r[row.id]);
        })
        .map(function (r) {
          return q.columns.indexOf(r[row.id]) + 1;
        });
      var top = d.items.slice(-2).reduce(function (sum, item) {
        return sum + item.count;
      }, 0);
      return { id: row.id, label: row.short, n: d.n, parts: d.items, mean: mean(scores), top: pct(top, d.n) };
    });
    var indexed = records.map(function (r) {
      var scores = q.rows
        .filter(function (row) {
          return has(r[row.id]);
        })
        .map(function (row) {
          return q.columns.indexOf(r[row.id]) + 1;
        });
      return { _band: r._band, _index: scores.length === q.rows.length ? mean(scores) : null };
    });
    return {
      id: q.id,
      label: q.text,
      prompt: q.prompt || "",
      columns: q.columns,
      items: items,
      index: mean(
        indexed.map(function (r) {
          return r._index;
        })
      ),
      byBand: meanByBand(indexed, "_index", bandLabels, minCell)
    };
  }

  function timeline(records) {
    var counts = {};
    records.forEach(function (r) {
      var day = String(r.submitted || "").slice(0, 10);
      if (/^\d{4}-\d{2}-\d{2}$/.test(day)) counts[day] = (counts[day] || 0) + 1;
    });
    var days = Object.keys(counts).sort();
    if (!days.length) return { n: 0, items: [] };
    var items = [];
    var cursor = new Date(days[0] + "T00:00:00Z");
    var last = new Date(days[days.length - 1] + "T00:00:00Z");
    var running = 0;
    while (cursor <= last && items.length < 400) {
      var key = cursor.toISOString().slice(0, 10);
      running += counts[key] || 0;
      items.push({ label: key, count: counts[key] || 0, cumulative: running });
      cursor.setUTCDate(cursor.getUTCDate() + 1);
    }
    return { n: running, items: items };
  }

  function keywords(records, key, minCount) {
    var tally = {};
    records.forEach(function (r) {
      var seen = {};
      String(r[key] || "")
        .toLowerCase()
        .replace(/[^a-z\s'-]/g, " ")
        .split(/\s+/)
        .forEach(function (word) {
          word = word.replace(/^['-]+|['-]+$/g, "");
          if (word.length < 4 || STOPWORDS.indexOf(word) !== -1 || seen[word]) return;
          seen[word] = true;
          tally[word] = (tally[word] || 0) + 1;
        });
    });
    return Object.keys(tally)
      .filter(function (word) {
        return tally[word] >= minCount;
      })
      .sort(function (a, b) {
        return tally[b] - tally[a] || (a < b ? -1 : 1);
      })
      .slice(0, 30)
      .map(function (word) {
        return { label: word, count: tally[word] };
      });
  }

  function texts(records, key) {
    return records
      .filter(function (r) {
        return has(r[key]) && String(r[key]).trim().length > 1;
      })
      .sort(function (a, b) {
        return String(b.submitted || "") < String(a.submitted || "") ? -1 : 1;
      })
      .map(function (r) {
        return { text: String(r[key]).trim(), campus: r.CAMPUS || "", band: r._band, submitted: r.submitted || "" };
      });
  }

  function quality(records, study, q) {
    var scaleRows = [];
    study.analysis.scales.forEach(function (id) {
      q[id].rows.forEach(function (row) {
        scaleRows.push(row.id);
      });
    });
    var straight = count(records, function (r) {
      var answers = scaleRows.map(function (id) {
        return q[id].options.indexOf(r[id]);
      });
      return (
        answers.every(function (a) {
          return a !== -1;
        }) &&
        answers.every(function (a) {
          return a === answers[0];
        })
      );
    });
    return {
      n: records.length,
      fast: count(records, function (r) {
        return isFast(r, study);
      }),
      fastMinutes: study.analysis.fastMinutes,
      straightLiners: straight,
      medianMinutes: median(
        records.map(function (r) {
          return r.minutes;
        })
      )
    };
  }

  function analyse(input, study, options) {
    options = options || {};
    var minCell = options.minCell || 0;
    var plan = study.analysis;
    var q = questionMap(study);
    var fies = study.scoring.fies;
    var idds = study.scoring.idds;
    var bandLabels = fies.categories.map(function (c) {
      return c.label;
    });
    var iddsLabels = idds.categories.map(function (c) {
      return c.label;
    });
    var records = prepare(input, study);
    var n = records.length;
    var insecureCount = count(records, function (r) {
      return r._insecure;
    });

    function fiesValues(key) {
      return records.map(function (r) {
        return r[key];
      });
    }

    var outcomes = plan.outcomes.map(function (rule) {
      return outcome(records, rule, minCell);
    });

    return {
      n: n,
      minCell: minCell,
      bands: bandLabels,
      iddsBands: iddsLabels,
      kpis: {
        insecure: proportion(insecureCount, n),
        severe: proportion(
          count(records, function (r) {
            return r._severe;
          }),
          n
        ),
        any: proportion(
          count(records, function (r) {
            return r._fies > 0;
          }),
          n
        ),
        meanFies: mean(fiesValues("_fies")),
        meanIdds: mean(fiesValues("_idds")),
        lowDiversity: proportion(
          count(records, function (r) {
            return r._iddsBand === iddsLabels[0];
          }),
          n
        )
      },
      timeline: timeline(records),
      sample: plan.sample.map(function (id) {
        return { id: id, label: q[id].short, dist: dist(records, id, q[id].options, minCell) };
      }),
      fies: {
        bands: dist(records, "_band", bandLabels, minCell),
        items: fies.items.map(function (id) {
          var yes = count(records, function (r) {
            return r[id] === fies.yes;
          });
          return { id: id, label: q[id].short, count: yes, pct: pct(yes, n) };
        }),
        scores: histogram(records, "_fies", 0, fies.items.length),
        iddsByBand: meanByBand(records, "_idds", bandLabels, minCell)
      },
      idds: {
        bands: dist(records, "_iddsBand", iddsLabels, minCell),
        scores: histogram(records, "_idds", 0, q[idds.question].options.length),
        groups: multi(records, idds.question, q[idds.question].options, true)
      },
      determinants: plan.determinants.map(function (group) {
        return {
          group: group.group,
          items: group.ids.map(function (id) {
            return determinant(records, q[id], minCell);
          })
        };
      }),
      outcomes: outcomes,
      diet: {
        meals: dist(records, plan.diet.meals, q[plan.diet.meals].options, minCell),
        mealsByBand: byBand(records, plan.diet.meals, q[plan.diet.meals].options, bandLabels, minCell),
        places: multi(records, plan.diet.places, q[plan.diet.places].options, false)
      },
      consequences: {
        lectures: dist(records, plan.consequences.lectures, q[plan.consequences.lectures].options, minCell),
        lecturesByBand: byBand(records, plan.consequences.lectures, q[plan.consequences.lectures].options, bandLabels, minCell),
        coping: multi(records, plan.consequences.coping, q[plan.consequences.coping].options, false),
        scales: plan.scales.map(function (id) {
          return scale(records, q[id], bandLabels, minCell);
        }),
        health: dist(records, plan.consequences.health, q[plan.consequences.health].options, minCell),
        healthByBand: byBand(records, plan.consequences.health, q[plan.consequences.health].options, bandLabels, minCell),
        social: q[plan.consequences.social].rows.map(function (row) {
          return outcome(records, { id: row.id, label: row.short, any: ["Yes"] }, minCell);
        })
      },
      support: {
        awareness: q[plan.support.awareness].rows.map(function (row) {
          var d = dist(records, row.id, q[row.id].options, 0);
          return { id: row.id, label: row.short, n: d.n, parts: d.items };
        }),
        accessed: dist(records, plan.support.accessed, q[plan.support.accessed].options, minCell),
        accessedByBand: byBand(records, plan.support.accessed, q[plan.support.accessed].options, bandLabels, minCell)
      },
      voices: {
        responses: count(records, function (r) {
          return has(r[plan.voices.recommendations]);
        }),
        keywords: keywords(records, plan.voices.recommendations, options.includeText ? 1 : Math.max(2, minCell)),
        recommendations: options.includeText ? texts(records, plan.voices.recommendations) : null,
        programmes: options.includeText ? texts(records, plan.voices.programmes) : null
      },
      quality: quality(records, study, q)
    };
  }

  return {
    analyse: analyse,
    filter: filter,
    questionMap: questionMap,
    chiSquare: chiSquare,
    proportion: proportion
  };
})();

if (typeof module !== "undefined" && module.exports) module.exports = StudyAnalytics;
