const fs = require("fs");
const path = require("path");

const RUNTIME = path.join(__dirname, "sheet-runtime.gs");
const ANALYTICS = path.join(__dirname, "../../../js/research-analytics.js");

function renderStudyAppsScript(study) {
  const runtime = fs.readFileSync(RUNTIME, "utf8");
  const analytics = fs.readFileSync(ANALYTICS, "utf8");
  return `/**
 * ${study.institution} — ${study.title}
 * Google Sheet inbox for the online questionnaire at /kiu-food-study/
 * and data feed for the live dashboard at /kiu-food-study/dashboard/.
 *
 * GENERATED by scripts/build-content.js from scripts/lib/research/kiu-food-study.js,
 * scripts/lib/research/sheet-runtime.gs and js/research-analytics.js. Edit those files, rebuild, then paste this file again.
 *
 * Creates three tabs:
 *   Responses  one row per respondent, with computed FIES and IDDS scores
 *   Summary    live totals by campus, FIES category and IDDS class
 *   Codebook   every column with the verbatim question and its coding
 *
 * Setup (once), signed into the Learn n'lunch Google account:
 * 1. Create a new Google Sheet for this study and keep its sharing Restricted
 * 2. Extensions → Apps Script, delete the default code and paste this entire file
 * 3. Save, then Run → setupWorkbook (Authorize when Google asks)
 * 4. Deploy → New deployment → Type: Web app
 *      Execute as: Me
 *      Who has access: Anyone
 * 5. Copy the web app URL into content/pages/kiu-food-study.md as submitEndpoint and rebuild the site
 *
 * After changing the questionnaire: paste this file over the old code, Save, Run → setupWorkbook,
 * then Deploy → Manage deployments → Edit (pencil) → Version: New version → Deploy (same URL).
 * New columns are inserted before "Notes"; existing rows are left untouched.
 *
 * Live dashboard:
 *   Run → showDashboardKey      prints the research team's access key in the execution log
 *   Run → resetDashboardKey     issues a new key (the old one stops working)
 *   Run → openDashboardToPublic / closeDashboardToPublic   presentation-day switch (also available on the dashboard)
 *   Type EXCLUDE at the start of a response's Notes cell to drop it from the dashboard.
 */

// Leave empty when this script is bound to the study spreadsheet (Extensions → Apps Script).
var SPREADSHEET_ID = "";

var STUDY = ${JSON.stringify(study, null, 2)};

${runtime}
${analytics}`;
}

module.exports = { renderStudyAppsScript };
