var RESPONSES_TAB = "Responses";
var SUMMARY_TAB = "Summary";
var CODEBOOK_TAB = "Codebook";
var TIMEZONE = "Africa/Kampala";
var NOTES_HEADER = "Notes";
var ID_HEADER = "Response ID";
var NUMBER_HEADER = "Questionnaire No.";
var DASHBOARD_KEY_PROP = "DASHBOARD_KEY";
var DASHBOARD_PUBLIC_PROP = "DASHBOARD_PUBLIC";
var PUBLIC_CACHE_KEY = "dashboard-public";
var PUBLIC_CACHE_SECONDS = 60;

function getSpreadsheet() {
  if (SPREADSHEET_ID) return SpreadsheetApp.openById(SPREADSHEET_ID);
  return SpreadsheetApp.getActiveSpreadsheet();
}

function allQuestions() {
  var list = [];
  STUDY.sections.forEach(function (section) {
    section.questions.forEach(function (question) {
      list.push(question);
    });
  });
  return list;
}

function shortOption(label) {
  return String(label).split(" (e.g.")[0];
}

function asList(value) {
  if (Array.isArray(value)) return value;
  if (value === undefined || value === null || value === "") return [];
  return [String(value)];
}

function clean(value) {
  var text = Array.isArray(value) ? value.join("; ") : String(value === undefined || value === null ? "" : value);
  text = text.replace(/\s+$/g, "");
  // Stops spreadsheet formula injection from free-text answers.
  return /^[=+\-@]/.test(text) ? "'" + text : text;
}

function scoreBand(score, categories) {
  for (var i = 0; i < categories.length; i++) {
    if (score <= categories[i].max) return categories[i].label;
  }
  return "";
}

function fiesScore(data) {
  var fies = STUDY.scoring.fies;
  return fies.items.reduce(function (total, id) {
    return total + (data[id] === fies.yes ? 1 : 0);
  }, 0);
}

function iddsScore(data) {
  return asList(data[STUDY.scoring.idds.question]).length;
}

/** Column definitions: header, question text for the codebook, coding note, and how to read the value. */
function columns() {
  var cols = [
    { header: NUMBER_HEADER, text: "Sequential questionnaire number assigned on receipt", coding: "KIU-0001, KIU-0002, …", meta: "number" },
    { header: ID_HEADER, text: "Unique ID generated by the respondent's browser; used to drop duplicate submissions", coding: "Text", meta: "responseId" },
    { header: "Submitted", text: "Date and time the response was received (Africa/Kampala)", coding: "Date/time", meta: "submitted" },
    { header: "Minutes to complete", text: "Time between opening the questionnaire and submitting it", coding: "Minutes", meta: "duration" },
    { header: "Form version", text: "Version of the questionnaire definition", coding: "Text", meta: "version" }
  ];

  allQuestions().forEach(function (q) {
    var code = q.code || q.id;
    if (q.type === "matrix") {
      q.rows.forEach(function (row) {
        cols.push({
          header: row.id + " · " + row.short,
          text: (q.prompt ? q.prompt + " " : "") + row.text,
          coding: q.columns.join(" / "),
          key: row.id
        });
      });
      return;
    }
    if (q.type === "checkbox") {
      cols.push({ header: code + " · " + q.short, text: q.text, coding: "Selected options, separated by ;", key: q.id, list: true });
      q.options.forEach(function (option, index) {
        var flagId = (q.flagPrefix || q.id + ".") + (index + 1);
        cols.push({ header: flagId + " · " + shortOption(option), text: q.text + " — " + option, coding: "1 = selected, 0 = not selected", key: q.id, flag: option });
      });
      return;
    }
    cols.push({
      header: code === q.short ? code : code + " · " + q.short,
      text: q.text,
      coding: q.optionsBy
        ? Object.keys(q.optionsBy)
            .map(function (parent) {
              return parent + ": " + q.optionsBy[parent].join(" / ");
            })
            .join("; ")
        : q.options
        ? q.options.join(" / ")
        : q.type === "number"
        ? "Number"
        : "Free text",
      key: q.id,
      numeric: q.type === "number"
    });
    if (q.other) {
      cols.push({ header: code + " · Other (specify)", text: q.text + " — Other (specify)", coding: "Free text", key: q.id + "_other" });
    }
    if (q.followUp) {
      cols.push({ header: code + " · " + q.followUp.short, text: q.text + " — " + q.followUp.text, coding: "Free text (asked if " + q.followUp.when + ")", key: q.followUp.id });
    }
  });

  cols.push({ header: "FIES raw score", text: "Sum of 'Yes' answers to D1–D8", coding: "0–8", computed: "fies" });
  cols.push({ header: "FIES category", text: "FIES raw score band", coding: "0 Food secure; 1–3 Mildly; 4–6 Moderately; 7–8 Severely food insecure", computed: "fiesBand" });
  cols.push({ header: "IDDS score", text: "Count of food groups selected in Section F", coding: "0–10", computed: "idds" });
  cols.push({ header: "IDDS class", text: "IDDS band", coding: "Low < 4; Medium 4–5; High ≥ 6", computed: "iddsBand" });
  cols.push({ header: NOTES_HEADER, text: "Research team notes (not part of the questionnaire)", coding: "Free text" });
  return cols;
}

function cellValue(col, data, number, now) {
  if (col.meta === "number") return "KIU-" + ("000" + number).slice(-4);
  if (col.meta === "responseId") return clean(data.responseId);
  if (col.meta === "submitted") return now;
  if (col.meta === "version") return clean(data.formVersion);
  if (col.meta === "duration") {
    var started = Date.parse(data.startedAt);
    return isNaN(started) ? "" : Math.max(0, Math.round(((now.getTime() - started) / 60000) * 10) / 10);
  }
  if (col.computed === "fies") return fiesScore(data);
  if (col.computed === "fiesBand") return scoreBand(fiesScore(data), STUDY.scoring.fies.categories);
  if (col.computed === "idds") return iddsScore(data);
  if (col.computed === "iddsBand") return scoreBand(iddsScore(data), STUDY.scoring.idds.categories);
  if (col.flag) return asList(data[col.key]).indexOf(col.flag) === -1 ? 0 : 1;
  if (col.key) {
    var value = data[col.key];
    if (col.list) return clean(asList(value));
    if (col.numeric && value !== "" && value !== undefined && !isNaN(Number(value))) return Number(value);
    return clean(value);
  }
  return "";
}

function doGet(e) {
  var params = (e && e.parameter) || {};
  if (params.view === "dashboard") return jsonOutput(dashboardPayload(params));
  return jsonOutput({ ok: true, study: STUDY.id, version: STUDY.version });
}

/**
 * Live dashboard feed. The research team (correct key) receives anonymised records, with no IDs or 24-hour recall,
 * so the page can filter them. Everyone else gets nothing until the team opens the dashboard to the public; then
 * they receive aggregated results only, with groups under analysis.publicMinCell suppressed.
 */
function dashboardPayload(params) {
  var props = PropertiesService.getScriptProperties();
  var key = props.getProperty(DASHBOARD_KEY_PROP);
  var isTeam = Boolean(key) && params.key === key;
  var cache = CacheService.getScriptCache();

  if (isTeam && (params.public === "on" || params.public === "off")) {
    props.setProperty(DASHBOARD_PUBLIC_PROP, params.public);
    cache.remove(PUBLIC_CACHE_KEY);
  }
  var isPublic = props.getProperty(DASHBOARD_PUBLIC_PROP) === "on";
  var generatedAt = new Date().toISOString();

  if (isTeam) {
    var team = readRecords(true);
    return { ok: true, mode: "team", public: isPublic, generatedAt: generatedAt, excluded: team.excluded, records: team.records };
  }
  if (!isPublic) return { ok: false, error: params.key ? "wrong-key" : "locked" };

  var cached = cache.get(PUBLIC_CACHE_KEY);
  var payload = cached ? JSON.parse(cached) : null;
  if (!payload) {
    var data = readRecords(false);
    payload = {
      ok: true,
      mode: "public",
      public: true,
      generatedAt: generatedAt,
      excluded: data.excluded,
      analysis: StudyAnalytics.analyse(data.records, STUDY, { minCell: STUDY.analysis.publicMinCell, includeText: false })
    };
    cache.put(PUBLIC_CACHE_KEY, JSON.stringify(payload), PUBLIC_CACHE_SECONDS);
  }
  payload.keyRejected = Boolean(params.key);
  return payload;
}

/** Reads Responses back into records keyed by question ID. Rows whose Notes start with "exclude" are left out. */
function readRecords(includeText) {
  var sheet = getSpreadsheet().getSheetByName(RESPONSES_TAB);
  if (!sheet || sheet.getLastRow() < 2) return { records: [], excluded: 0 };

  var values = sheet.getRange(1, 1, sheet.getLastRow(), sheet.getLastColumn()).getValues();
  var headers = values[0].map(function (value) {
    return String(value || "").trim();
  });
  var byHeader = {};
  columns().forEach(function (col) {
    byHeader[col.header] = col;
  });

  var textKeys = {};
  allQuestions().forEach(function (q) {
    if (q.type === "textarea" || q.type === "text") textKeys[q.id] = true;
    if (q.other) textKeys[q.id + "_other"] = true;
    if (q.followUp) textKeys[q.followUp.id] = true;
  });
  var allowedText = {};
  if (includeText) {
    STUDY.analysis.textFields.forEach(function (id) {
      allowedText[id] = true;
    });
  }

  var notesIndex = headers.indexOf(NOTES_HEADER);
  var excluded = 0;
  var records = [];
  for (var r = 1; r < values.length; r++) {
    var row = values[r];
    if (notesIndex !== -1 && /^\s*exclude/i.test(String(row[notesIndex] || ""))) {
      excluded++;
      continue;
    }
    var record = {};
    var hasAnswers = false;
    headers.forEach(function (header, c) {
      var col = byHeader[header];
      var value = row[c];
      if (!col || col.flag || col.computed) return;
      if (col.meta === "submitted") {
        if (value instanceof Date) record.submitted = Utilities.formatDate(value, TIMEZONE, "yyyy-MM-dd'T'HH:mm");
        return;
      }
      if (col.meta === "duration") {
        if (value !== "" && !isNaN(Number(value))) record.minutes = Number(value);
        return;
      }
      if (!col.key) return;
      if (textKeys[col.key] && !allowedText[col.key]) return;
      if (value === "" || value === null) return;
      hasAnswers = true;
      if (col.list) record[col.key] = String(value).split(/;\s*/);
      else if (col.numeric) record[col.key] = Number(value);
      else record[col.key] = String(value);
    });
    if (hasAnswers) records.push(record);
  }
  return { records: records, excluded: excluded };
}

/** Run once from the editor: creates the dashboard access key (if missing) and prints it in the execution log. */
function showDashboardKey() {
  var props = PropertiesService.getScriptProperties();
  var key = props.getProperty(DASHBOARD_KEY_PROP);
  if (!key) {
    key = Utilities.getUuid().replace(/-/g, "").slice(0, 12);
    props.setProperty(DASHBOARD_KEY_PROP, key);
  }
  Logger.log("Dashboard access key: " + key + " (public: " + (props.getProperty(DASHBOARD_PUBLIC_PROP) === "on") + ")");
  return key;
}

/** Replaces the access key; anyone holding the old key loses access. */
function resetDashboardKey() {
  PropertiesService.getScriptProperties().deleteProperty(DASHBOARD_KEY_PROP);
  return showDashboardKey();
}

function openDashboardToPublic() {
  PropertiesService.getScriptProperties().setProperty(DASHBOARD_PUBLIC_PROP, "on");
  CacheService.getScriptCache().remove(PUBLIC_CACHE_KEY);
}

function closeDashboardToPublic() {
  PropertiesService.getScriptProperties().setProperty(DASHBOARD_PUBLIC_PROP, "off");
  CacheService.getScriptCache().remove(PUBLIC_CACHE_KEY);
}

function doPost(e) {
  if (!e || !e.postData || !e.postData.contents) return jsonOutput({ ok: false, error: "Empty body" });

  var data;
  try {
    data = JSON.parse(e.postData.contents);
  } catch (error) {
    return jsonOutput({ ok: false, error: "Invalid JSON" });
  }
  if (data._gotcha) return jsonOutput({ ok: true, ignored: true });
  if (!data.responseId) return jsonOutput({ ok: false, error: "Missing responseId" });
  if (data[STUDY.consent.question] !== STUDY.consent.yes || data[STUDY.consent.ageQuestion] !== STUDY.consent.ageYes) {
    return jsonOutput({ ok: false, error: "Not eligible" });
  }

  var lock = LockService.getScriptLock();
  lock.waitLock(20000);
  try {
    var sheet = ensureResponsesSheet(getSpreadsheet());
    var headers = readHeaders(sheet);
    var idCol = headers.indexOf(ID_HEADER) + 1;
    if (idCol > 0 && sheet.getLastRow() > 1) {
      var found = sheet
        .getRange(2, idCol, sheet.getLastRow() - 1, 1)
        .createTextFinder(String(data.responseId))
        .matchEntireCell(true)
        .findNext();
      if (found) return jsonOutput({ ok: true, duplicate: true });
    }

    var byHeader = {};
    var now = new Date();
    var number = sheet.getLastRow();
    columns().forEach(function (col) {
      byHeader[col.header] = cellValue(col, data, number, now);
    });
    sheet.appendRow(
      headers.map(function (header) {
        return Object.prototype.hasOwnProperty.call(byHeader, header) ? byHeader[header] : "";
      })
    );
    return jsonOutput({ ok: true });
  } catch (error) {
    return jsonOutput({ ok: false, error: String(error) });
  } finally {
    lock.releaseLock();
  }
}

function readHeaders(sheet) {
  var lastColumn = sheet.getLastColumn();
  if (lastColumn < 1) return [];
  return sheet
    .getRange(1, 1, 1, lastColumn)
    .getValues()[0]
    .map(function (value) {
      return String(value || "").trim();
    });
}

function columnLetter(index) {
  var letters = "";
  while (index > 0) {
    var remainder = (index - 1) % 26;
    letters = String.fromCharCode(65 + remainder) + letters;
    index = Math.floor((index - 1) / 26);
  }
  return letters;
}

/** Creates the Responses tab or adds any new columns before Notes, without moving existing data. */
function ensureResponsesSheet(spreadsheet) {
  var sheet = spreadsheet.getSheetByName(RESPONSES_TAB) || spreadsheet.insertSheet(RESPONSES_TAB, 0);
  var wanted = columns().map(function (col) {
    return col.header;
  });
  var existing = readHeaders(sheet);
  var hasHeaders = existing.some(function (header) {
    return header !== "";
  });

  if (!hasHeaders) {
    sheet.getRange(1, 1, 1, wanted.length).setValues([wanted]);
    styleResponses(sheet, wanted.length);
    return sheet;
  }

  var missing = wanted.filter(function (header) {
    return existing.indexOf(header) === -1;
  });
  if (missing.length) {
    var notesCol = existing.indexOf(NOTES_HEADER) + 1;
    if (notesCol > 0) {
      sheet.insertColumnsBefore(notesCol, missing.length);
      sheet.getRange(1, notesCol, 1, missing.length).setValues([missing]);
    } else {
      sheet.getRange(1, existing.length + 1, 1, missing.length).setValues([missing]);
    }
    styleResponses(sheet, readHeaders(sheet).length);
  }
  return sheet;
}

function styleResponses(sheet, width) {
  var header = sheet.getRange(1, 1, 1, width);
  header.setFontWeight("bold").setBackground("#f6c33c").setFontColor("#000000").setWrap(true).setVerticalAlignment("top");
  sheet.setFrozenRows(1);
  sheet.setFrozenColumns(2);
  sheet.setRowHeight(1, 54);
  sheet.setColumnWidths(1, width, 150);
}

function setupWorkbook() {
  var spreadsheet = getSpreadsheet();
  spreadsheet.setSpreadsheetTimeZone(TIMEZONE);
  var sheet = ensureResponsesSheet(spreadsheet);
  writeCodebook(spreadsheet);
  writeSummary(spreadsheet, readHeaders(sheet));
  showDashboardKey();
}

function writeCodebook(spreadsheet) {
  var sheet = spreadsheet.getSheetByName(CODEBOOK_TAB) || spreadsheet.insertSheet(CODEBOOK_TAB);
  sheet.clear();
  var rows = [["Column", "Question (verbatim)", "Response options / coding"]];
  columns().forEach(function (col) {
    rows.push([col.header, col.text || "", col.coding || ""]);
  });
  sheet.getRange(1, 1, rows.length, 3).setValues(rows).setWrap(true).setVerticalAlignment("top");
  sheet.getRange(1, 1, 1, 3).setFontWeight("bold").setBackground("#f6c33c");
  sheet.setFrozenRows(1);
  sheet.setColumnWidth(1, 260);
  sheet.setColumnWidth(2, 520);
  sheet.setColumnWidth(3, 320);
}

function writeSummary(spreadsheet, headers) {
  var sheet = spreadsheet.getSheetByName(SUMMARY_TAB) || spreadsheet.insertSheet(SUMMARY_TAB);
  sheet.clear();

  function col(header) {
    var index = headers.indexOf(header) + 1;
    return index > 0 ? "'" + RESPONSES_TAB + "'!" + columnLetter(index) + "2:" + columnLetter(index) : null;
  }
  var idRange = col(ID_HEADER);
  var total = "COUNTA(" + idRange + ")";
  var campusRange = col("Campus");
  var fiesBand = col("FIES category");
  var iddsBand = col("IDDS class");

  var rows = [
    [STUDY.institution, ""],
    ["Food insecurity study — live summary", ""],
    ["", ""],
    ["Total responses", "=" + total],
    ["Mean FIES raw score", "=IFERROR(ROUND(AVERAGE(" + col("FIES raw score") + "),2),\"\")"],
    ["Mean IDDS score", "=IFERROR(ROUND(AVERAGE(" + col("IDDS score") + "),2),\"\")"],
    ["Median minutes to complete", "=IFERROR(MEDIAN(" + col("Minutes to complete") + "),\"\")"],
    ["", ""],
    ["Campus", "Responses"]
  ];
  var campusQuestion = allQuestions().filter(function (q) {
    return q.id === "CAMPUS";
  })[0];
  campusQuestion.options.forEach(function (option) {
    rows.push([option, "=COUNTIF(" + campusRange + ",\"" + option + "\")"]);
  });
  rows.push(["", ""], ["FIES category", "Responses"]);
  STUDY.scoring.fies.categories.forEach(function (band) {
    rows.push([band.label, "=COUNTIF(" + fiesBand + ",\"" + band.label + "\")"]);
  });
  rows.push(["", ""], ["IDDS class", "Responses"]);
  STUDY.scoring.idds.categories.forEach(function (band) {
    rows.push([band.label, "=COUNTIF(" + iddsBand + ",\"" + band.label + "\")"]);
  });

  sheet.getRange(1, 1, rows.length, 2).setValues(rows);
  sheet.getRange("A1").setFontWeight("bold").setFontSize(14);
  sheet.getRange("A2").setFontStyle("italic");
  rows.forEach(function (row, index) {
    if (row[1] === "Responses") sheet.getRange(index + 1, 1, 1, 2).setFontWeight("bold").setBackground("#f6c33c");
  });
  sheet.setColumnWidth(1, 300);
  sheet.setColumnWidth(2, 140);
}

function jsonOutput(payload) {
  return ContentService.createTextOutput(JSON.stringify(payload)).setMimeType(ContentService.MimeType.JSON);
}
